replicaCount: 1

image:
  repository: opencloudeu/opencloud-rolling
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

opencloud:
  domain: "cloud.scheeps.online"

  adminPasswordSecret:
    name: "opencloud-admin-secret"
    key: "password"

  logLevel: "info"
  logColor: false
  logPretty: false

  insecure: true
  enableBasicAuth: false

  createDemoUsers: false

storage:
  data:
    enabled: true
    claimName: "opencloud-unas-pvc"
    mountPath: "/var/lib/opencloud/"

  cache:
    enabled: true
    claimName: "opencloud-cache-pvc"
    mountPath: "/var/cache/ocis"

  config:
    enabled: true
    claimName: "opencloud-config-pvc"
    mountPath: "/etc/opencloud"

service:
  type: ClusterIP
  port: 9200
  targetPort: 9200

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

podSecurityContext:
  fsGroup: 1000

env:
  - name: OCIS_LOG_LEVEL
    value: "info"
  - name: OCIS_LOG_COLOR
    value: "false"
  - name: OCIS_LOG_PRETTY
    value: "false"
