replicaCount: 1

image:
  repository: opencloud/opencloud
  tag: 2.0.2
  pullPolicy: IfNotPresent

db:
  host: pgbouncer.opencloud.svc.cluster.local
  port: 5432
  name: opencloud

persistence:
  userdata:
    enabled: true
    existingClaim: opencloud-userdata-pvc
    mountPath: /var/www/html/data

  config:
    enabled: true
    existingClaim: opencloud-config-pvc
    mountPath: /var/www/html/config

  cache:
    enabled: true
    existingClaim: opencloud-cache-pvc
    mountPath: /var/www/html/cache

secrets:
  db:
    name: opencloud-pg-secret
    userKey: username
    passwordKey: password
  admin:
    name: opencloud-admin-secret
    userKey: username
    passwordKey: password

service:
  type: ClusterIP
  port: 8080

securityContext:
  runAsUser: 977
  runAsGroup: 988
  fsGroup: 988

resources: {}

timezone: "Europe/London"
