replicaCount: 1

image:
  repository: opencloudeu/opencloud-rolling
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

opencloud:
  domain: "opencloud.local"

  adminPasswordSecret:
    name: "opencloud-admin-secret"
    key: "password"

  jwtSecretSecret:
    name: "opencloud-jwt-secret"
    key: "jwt_secret"

  logLevel: "info"
  logColor: false
  logPretty: false

  insecure: true
  enableBasicAuth: false

  createDemoUsers: false

database:
  external:
    enabled: true
    host: "pgbouncer"
    port: 5432
    database: "opencloud"
    username: "opencloud"
    passwordSecret:
      name: "opencloud-pg-secret"
      key: "password"
    sslmode: "disable"

storage:
  data:
    enabled: true
    claimName: "opencloud-unas-pvc"
    mountPath: "/var/lib/ocis/data"

  config:
    enabled: true
    claimName: "opencloud-config-pvc"
    mountPath: "/etc/ocis"

  cache:
    enabled: true
    claimName: "opencloud-cache-pvc"
    mountPath: "/var/cache/ocis"

service:
  type: ClusterIP
  port: 9200
  targetPort: 9200

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

podSecurityContext:
  fsGroup: 1000

env:
  - name: OCIS_LOG_LEVEL
    value: "info"
  - name: OCIS_LOG_COLOR
    value: "false"
  - name: OCIS_LOG_PRETTY
    value: "false"
