# Default values for node-red
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nodered/node-red
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 1880
  name: http

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Persistence configuration (PVC managed outside helm)
persistence:
  # Name of existing PVC
  existingClaim: "nodered-config"
  mountPath: "/data"

# Node-RED Configuration
nodeRed:
  # Timezone
  timezone: "America/New_York"
  
  # Enable projects feature
  enableProjects: true
  
  # Node-RED settings
  settings: |
    module.exports = {
        uiPort: process.env.PORT || 1880,
        mqttReconnectTime: 15000,
        serialReconnectTime: 15000,
        debugMaxLength: 1000,
        functionGlobalContext: {
        },
        exportGlobalContextKeys: false,
        logging: {
            console: {
                level: "info",
                metrics: false,
                audit: false
            }
        },
        editorTheme: {
            projects: {
                enabled: true
            }
        }
    };

# External Secret reference (managed outside helm)
secrets:
  # Name of the existing secret for OAuth2 authentication
  authSecret: "nodered-auth-secret"

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext:
  fsGroup: 1000

# Security context
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true

# Service account
serviceAccount:
  create: true
  annotations: {}
  name: ""