apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "n8n.configMapName" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}
  N8N_HOST: {{ .Values.config.N8N_HOST | quote }}
  N8N_PORT: {{ .Values.config.N8N_PORT | quote }}
  N8N_PROTOCOL: {{ .Values.config.N8N_PROTOCOL | quote }}
  WEBHOOK_URL: {{ .Values.config.WEBHOOK_URL | quote }}
  N8N_LOG_LEVEL: {{ .Values.config.N8N_LOG_LEVEL | quote }}
  N8N_METRICS: {{ .Values.config.N8N_METRICS | quote }}
  N8N_DIAGNOSTICS_ENABLED: {{ .Values.config.N8N_DIAGNOSTICS_ENABLED | quote }}
  N8N_PERSONALIZATION_ENABLED: {{ .Values.config.N8N_PERSONALIZATION_ENABLED | quote }}
  N8N_VERSION_NOTIFICATIONS_ENABLED: {{ .Values.config.N8N_VERSION_NOTIFICATIONS_ENABLED | quote }}
  N8N_TEMPLATES_ENABLED: {{ .Values.config.N8N_TEMPLATES_ENABLED | quote }}
  N8N_PUBLIC_API_DISABLED: {{ .Values.config.N8N_PUBLIC_API_DISABLED | quote }}
  DB_TYPE: {{ .Values.db.type | quote }}
  DB_POSTGRESDB_HOST: {{ .Values.db.host | quote }}
  DB_POSTGRESDB_PORT: {{ .Values.db.port | quote }}
  DB_POSTGRESDB_DATABASE: {{ .Values.db.name | quote }}