{{- if .Values.main.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "n8n.pvcName" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.main.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.main.persistence.size }}
{{- end }}