apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prowlarr.fullname" . }}-config
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "prowlarr.labels" . | nindent 4 }}
data:
  config.xml: |
    <?xml version="1.0" encoding="utf-8" standalone="yes"?>
    <Config>
      <LogLevel>info</LogLevel>
      <UpdateMechanism>Docker</UpdateMechanism>
      <Branch>master</Branch>
      <ApiKey>{{ randAlphaNum 32 }}</ApiKey>
      <AuthenticationMethod>None</AuthenticationMethod>
      <LaunchBrowser>False</LaunchBrowser>
      <Port>9696</Port>
      <SslPort>6969</SslPort>
      <EnableSsl>False</EnableSsl>
      <UrlBase></UrlBase>
      <InstanceName>Prowlarr</InstanceName>
      
      <!-- PostgreSQL Configuration -->
      <PostgresHost>{{ .Values.db.host }}</PostgresHost>
      <PostgresPort>{{ .Values.db.port }}</PostgresPort>
      <PostgresMainDb>{{ .Values.db.name }}</PostgresMainDb>
      <PostgresLogDb>{{ .Values.db.name }}-log</PostgresLogDb>
      <!-- PostgresUser and PostgresPassword will be injected by init container -->
    </Config>