{{- if .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vlan-manager.labels" . | nindent 4 }}
{{- end }}