apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pgbouncer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pgbouncer.selectorLabels" . | nindent 8 }}
    spec:
      {{- if or .Values.auth.users (and .Values.auth.externalUserlist.enabled (or .Values.auth.externalUserlist.configMap .Values.auth.externalUserlist.secret)) }}
      initContainers:
      - name: auth-processor
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/bin/bash"]
        args:
        - -c
        - |
          #!/bin/bash
          set -e
          
          # Create processed userlist directory
          mkdir -p /tmp/pgbouncer
          
          # Process authentication configuration
          {{- if .Values.auth.externalUserlist.enabled }}
          {{- if or .Values.auth.externalUserlist.configMap .Values.auth.externalUserlist.secret }}
          # Use external userlist as-is
          cp /opt/bitnami/pgbouncer/conf/userlist.txt /tmp/pgbouncer/userlist.txt
          {{- end }}
          {{- else if .Values.auth.users }}
          # Generate userlist from user configurations
          cat > /tmp/pgbouncer/userlist.txt << 'EOF'
          {{- range .Values.auth.users }}
          {{- if .passwordSecret }}
          "{{ .name }}" "$(cat /opt/bitnami/pgbouncer/secrets/{{ .passwordSecret.name }}/{{ .passwordSecret.key }} | tr -d '\n' | python3 -c "
          import sys, hashlib, secrets, base64
          password = sys.stdin.read().strip()
          salt = secrets.token_bytes(16)
          key = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt, 4096, 32)
          stored_key = hashlib.sha256(key + b'Client Key').digest()
          server_key = hashlib.sha256(key + b'Server Key').digest()
          salt_b64 = base64.b64encode(salt).decode()
          stored_key_b64 = base64.b64encode(stored_key).decode()
          server_key_b64 = base64.b64encode(server_key).decode()
          print(f'SCRAM-SHA-256${4096}:{salt_b64}${stored_key_b64}:{server_key_b64}')
          ")"
          {{- else if .password }}
          "{{ .name }}" "$(echo -n '{{ .password }}' | python3 -c "
          import sys, hashlib, secrets, base64
          password = sys.stdin.read().strip()
          salt = secrets.token_bytes(16)
          key = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt, 4096, 32)
          stored_key = hashlib.sha256(key + b'Client Key').digest()
          server_key = hashlib.sha256(key + b'Server Key').digest()
          salt_b64 = base64.b64encode(salt).decode()
          stored_key_b64 = base64.b64encode(stored_key).decode()
          server_key_b64 = base64.b64encode(server_key).decode()
          print(f'SCRAM-SHA-256${4096}:{salt_b64}${stored_key_b64}:{server_key_b64}')
          ")"
          {{- end }}
          {{- end }}
          EOF
          {{- else }}
          # Use legacy static userlist
          cat > /tmp/pgbouncer/userlist.txt << 'EOF'
{{ .Values.auth.userlist }}
          EOF
          {{- end }}
          
          echo "Generated userlist:"
          cat /tmp/pgbouncer/userlist.txt
        volumeMounts:
        - name: processed-auth
          mountPath: /tmp/pgbouncer
        {{- if .Values.auth.externalUserlist.enabled }}
        - name: pgbouncer-userlist
          mountPath: /opt/bitnami/pgbouncer/conf
          readOnly: true
        {{- end }}
        {{- range .Values.auth.users }}
        {{- if .passwordSecret }}
        - name: user-secret-{{ .passwordSecret.name }}
          mountPath: /opt/bitnami/pgbouncer/secrets/{{ .passwordSecret.name }}
          readOnly: true
        {{- end }}
        {{- end }}
      {{- end }}
      containers:
      - name: pgbouncer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_HOST
          value: {{ .Values.postgresql.host | quote }}
        - name: POSTGRESQL_PORT
          value: "{{ .Values.postgresql.port }}"
        - name: POSTGRESQL_USERNAME
          value: {{ .Values.postgresql.username | quote }}
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.passwordSecret }}
              key: password
        - name: PGBOUNCER_AUTH_TYPE
          value: {{ .Values.auth.type | quote }}
        - name: PGBOUNCER_POOL_MODE
          value: {{ .Values.auth.poolMode | quote }}
        - name: PGBOUNCER_PORT
          value: "5432"
        {{- if or .Values.auth.users (and .Values.auth.externalUserlist.enabled (or .Values.auth.externalUserlist.configMap .Values.auth.externalUserlist.secret)) }}
        - name: PGBOUNCER_USERLIST_FILE
          value: "/opt/bitnami/pgbouncer/processed-auth/userlist.txt"
        {{- else }}
        - name: PGBOUNCER_USERLIST
          value: |-
{{ .Values.auth.userlist | indent 12 }}
        {{- end }}
        - name: PGBOUNCER_SERVER_TLS_SSLMODE
          value: {{ .Values.tls.sslMode | quote }}
        - name: PGBOUNCER_SERVER_TLS_CA_FILE
          value: "/opt/bitnami/pgbouncer/certs/ca.crt"
        - name: PGBOUNCER_SERVER_TLS_CERT_FILE
          value: "/opt/bitnami/pgbouncer/certs/tls.crt"
        - name: PGBOUNCER_SERVER_TLS_KEY_FILE
          value: "/opt/bitnami/pgbouncer/certs/tls.key"
        - name: PGBOUNCER_MIN_POOL_SIZE
          value: "{{ .Values.auth.minPoolSize }}"
        - name: PGBOUNCER_DATABASE
          value: {{ .Values.auth.database | quote }}
        - name: PGBOUNCER_IGNORE_STARTUP_PARAMETERS
          value: {{ .Values.auth.ignoreStartupParameters | quote }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: pgbouncer-server-tls
          mountPath: /opt/bitnami/pgbouncer/certs
          readOnly: true
        {{- if or .Values.auth.users (and .Values.auth.externalUserlist.enabled (or .Values.auth.externalUserlist.configMap .Values.auth.externalUserlist.secret)) }}
        - name: processed-auth
          mountPath: /opt/bitnami/pgbouncer/processed-auth
          readOnly: true
        {{- end }}
      volumes:
      - name: pgbouncer-server-tls
        secret:
          secretName: {{ .Values.tls.serverTlsSecret }}
      {{- if or .Values.auth.users (and .Values.auth.externalUserlist.enabled (or .Values.auth.externalUserlist.configMap .Values.auth.externalUserlist.secret)) }}
      - name: processed-auth
        emptyDir: {}
      {{- end }}
      {{- if .Values.auth.externalUserlist.enabled }}
      {{- if .Values.auth.externalUserlist.configMap }}
      - name: pgbouncer-userlist
        configMap:
          name: {{ .Values.auth.externalUserlist.configMap.name }}
          items:
          - key: {{ .Values.auth.externalUserlist.configMap.key }}
            path: userlist.txt
      {{- else if .Values.auth.externalUserlist.secret }}
      - name: pgbouncer-userlist
        secret:
          secretName: {{ .Values.auth.externalUserlist.secret.name }}
          items:
          - key: {{ .Values.auth.externalUserlist.secret.key }}
            path: userlist.txt
      {{- end }}
      {{- end }}
      {{- $secrets := dict }}
      {{- range .Values.auth.users }}
      {{- if .passwordSecret }}
      {{- $_ := set $secrets .passwordSecret.name true }}
      {{- end }}
      {{- end }}
      {{- range $secretName, $_ := $secrets }}
      - name: user-secret-{{ $secretName }}
        secret:
          secretName: {{ $secretName }}
      {{- end }}