apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pgbouncer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pgbouncer.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: auth-processor
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/bin/bash"]
        args:
        - -c
        - |
          #!/bin/bash
          set -e
          
          # Create processed userlist directory
          mkdir -p /tmp/pgbouncer
          
          # Generate userlist from user secret
          USERNAME=$(cat /opt/bitnami/pgbouncer/secrets/user-credentials/{{ .Values.auth.userSecret.usernameKey }} | tr -d '\n')
          PASSWORD=$(cat /opt/bitnami/pgbouncer/secrets/user-credentials/{{ .Values.auth.userSecret.passwordKey }} | tr -d '\n')
          
          # Use plain text passwords to allow PgBouncer to handle SCRAM authentication to backend
          echo "\"$USERNAME\" \"$PASSWORD\"" > /tmp/pgbouncer/userlist.txt
          
          echo "Generated userlist:"
          cat /tmp/pgbouncer/userlist.txt
        volumeMounts:
        - name: processed-auth
          mountPath: /tmp/pgbouncer
        - name: user-credentials-secret
          mountPath: /opt/bitnami/pgbouncer/secrets/user-credentials
          readOnly: true
      containers:
      - name: pgbouncer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_HOST
          value: {{ .Values.postgresql.host | quote }}
        - name: POSTGRESQL_PORT
          value: "{{ .Values.postgresql.port }}"
        - name: POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.connectionSecret.name }}
              key: {{ .Values.postgresql.connectionSecret.usernameKey }}
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.connectionSecret.name }}
              key: {{ .Values.postgresql.connectionSecret.passwordKey }}
        - name: PGBOUNCER_AUTH_TYPE
          value: {{ .Values.auth.type | quote }}
        - name: PGBOUNCER_POOL_MODE
          value: {{ .Values.auth.poolMode | quote }}
        - name: PGBOUNCER_PORT
          value: "5432"
        - name: PGBOUNCER_USERLIST_FILE
          value: "/opt/bitnami/pgbouncer/processed-auth/userlist.txt"
        - name: PGBOUNCER_SERVER_TLS_SSLMODE
          value: {{ .Values.tls.sslMode | quote }}
        - name: PGBOUNCER_SERVER_TLS_CA_FILE
          value: "/opt/bitnami/pgbouncer/certs/ca.crt"
        - name: PGBOUNCER_SERVER_TLS_CERT_FILE
          value: "/opt/bitnami/pgbouncer/certs/tls.crt"
        - name: PGBOUNCER_SERVER_TLS_KEY_FILE
          value: "/opt/bitnami/pgbouncer/certs/tls.key"
        - name: PGBOUNCER_MIN_POOL_SIZE
          value: "{{ .Values.auth.minPoolSize }}"
        - name: PGBOUNCER_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.auth.userSecret.name }}
              key: {{ .Values.auth.userSecret.databaseKey }}
        - name: PGBOUNCER_IGNORE_STARTUP_PARAMETERS
          value: {{ .Values.auth.ignoreStartupParameters | quote }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: pgbouncer-server-tls
          mountPath: /opt/bitnami/pgbouncer/certs
          readOnly: true
        - name: processed-auth
          mountPath: /opt/bitnami/pgbouncer/processed-auth
          readOnly: true
      volumes:
      - name: pgbouncer-server-tls
        secret:
          secretName: {{ .Values.tls.serverTlsSecret }}
      - name: processed-auth
        emptyDir: {}
      - name: user-credentials-secret
        secret:
          secretName: {{ .Values.auth.userSecret.name }}