apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  configuration.yaml: |
    # Home Assistant reverse proxy configuration
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        {{- range .Values.homeAssistant.trustedProxies }}
        - {{ . }}
        {{- end }}

    # Default configuration
    default_config:

    {{- if .Values.database.enabled }}
    # Database configuration
    recorder:
      db_url: !env_var DATABASE_URL
    {{- end }}

