apiVersion: v1
kind: Service
metadata:
  name: { { .Chart.Name } }
  namespace: { { .Values.namespace } }
  annotations: { { - toYaml .Values.service.annotations | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  selector:
    app: { { .Chart.Name } }
  ports:
    - name: http
      port: { { .Values.proxy.httpPort } }
      targetPort: http
    - name: socks
      port: { { .Values.proxy.socksPort } }
      targetPort: socks
    - name: metrics
      port: { { .Values.prometheus.port } }
      targetPort: metrics
