# VLAN Manager Helm Chart Values
global:
  namespace: network-management
  
  # Common image settings
  image:
    tag: "2.0.0"
    pullPolicy: Always
    pullSecrets:
      - name: docker-hub-secret
  
  # Shared database configuration
  database:
    host: "pgbouncer.network-management.svc.cluster.local"
    port: "5432"
    name: "freeradius"
    user: "freeradius"
    secret:
      name: freeradius-pg-secret
      passwordKey: password
  
  # Common resource profiles
  resources:
    small:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    medium:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    large:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# API Configuration
api:
  enabled: true
  replicaCount: 2
  
  image:
    repository: theunis/vlan-manager-api
  
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  
  serviceAccount:
    create: true
    name: vlan-manager-api
  
  # Uses global.database config
  
  resourceProfile: large  # References global.resources.large
  
  probes:
    liveness:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
    readiness:
      httpGet:
        path: /ready
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 5

# Frontend Configuration  
frontend:
  enabled: true
  replicaCount: 2
  
  image:
    repository: theunis/vlan-manager-frontend
  
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  
  resourceProfile: small  # References global.resources.small

# Notification Service Configuration
notification:
  enabled: true
  replicaCount: 1  # Only one replica to avoid duplicate notifications
  
  image:
    repository: theunis/vlan-manager-notification
  
  # Uses global.database config + unique secrets
  secrets:
    telegram:
      secretName: telegram-bot-secret
      tokenKey: token
      chatIdKey: chat_id
  
  resourceProfile: medium  # References global.resources.medium

# Sync Service Configuration (for manual job template only)
sync:
  image:
    repository: theunis/vlan-manager-sync
  
  job:
    ttlSecondsAfterFinished: 3600  # 1 hour for manual jobs
  
  # Uses global.database config (postgres env vars) + unique secrets
  secrets:
    unifi:
      secretName: unifi-credentials
      controllerUrlKey: controller_url
      usernameKey: username
      passwordKey: password

# ConfigMaps
configMaps:
  unifiFieldMappings:
    enabled: true
    data:
      field_mappings.yaml: |
        # UniFi field mappings configuration
        device_fields:
          mac: "mac"
          name: "name"
          model: "model"
          ip: "ip"
          last_seen: "last_seen"
          adopted: "adopted"
          disabled: "disabled"
  
  syncJobTemplate:
    enabled: true