{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vlan-manager.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vlan-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "vlan-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}