{{- if .Values.configMaps.unifiFieldMappings.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vlan-manager.fullname" . }}-unifi-field-mappings
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vlan-manager.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMaps.unifiFieldMappings.data | nindent 2 }}
{{- end }}
---
{{- if .Values.configMaps.syncJobTemplate.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vlan-manager.fullname" . }}-sync-job-template
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vlan-manager.labels" . | nindent 4 }}
data:
  job.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      generateName: {{ include "vlan-manager.fullname" . }}-sync-manual-
      namespace: {{ .Values.global.namespace }}
      labels:
        {{- include "vlan-manager.labels" . | nindent 8 }}
        app.kubernetes.io/component: sync
    spec:
      ttlSecondsAfterFinished: {{ .Values.sync.job.ttlSecondsAfterFinished }}
      template:
        spec:
          containers:
          - name: sync
            image: "{{ .Values.sync.image.repository }}:{{ .Values.sync.image.tag | default .Values.global.image.tag }}"
            env:
            - name: UNIFI_CONTROLLER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sync.secrets.unifi.secretName }}
                  key: {{ .Values.sync.secrets.unifi.controllerUrlKey }}
            - name: UNIFI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sync.secrets.unifi.secretName }}
                  key: {{ .Values.sync.secrets.unifi.usernameKey }}
            - name: UNIFI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sync.secrets.unifi.secretName }}
                  key: {{ .Values.sync.secrets.unifi.passwordKey }}
            - name: POSTGRES_HOST
              value: {{ .Values.global.database.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.global.database.port | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.global.database.name | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.global.database.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.database.secret.name }}
                  key: {{ .Values.global.database.secret.passwordKey }}
            volumeMounts:
            - name: config
              mountPath: /config/field_mappings.yaml
              subPath: field_mappings.yaml
              readOnly: true
          volumes:
          - name: config
            configMap:
              name: {{ include "vlan-manager.fullname" . }}-unifi-field-mappings
          restartPolicy: OnFailure
          {{- if .Values.global.image.pullSecrets }}
          imagePullSecrets:
            {{- toYaml .Values.global.image.pullSecrets | nindent 10 }}
          {{- end }}
{{- end }}
---
{{- if .Values.configMaps.dbCleanupScript.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vlan-manager.fullname" . }}-db-cleanup-script
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vlan-manager.labels" . | nindent 4 }}
data:
  cleanup.sql: |
    -- Delete device status older than {{ .Values.configMaps.dbCleanupScript.retentionPeriods.deviceStatus }}
    DELETE FROM device_status
    WHERE sync_time < (CURRENT_TIMESTAMP - INTERVAL '{{ .Values.configMaps.dbCleanupScript.retentionPeriods.deviceStatus }}');

    -- Delete processed notifications older than {{ .Values.configMaps.dbCleanupScript.retentionPeriods.processedNotifications }}
    DELETE FROM notification_queue
    WHERE processed = true
    AND processed_at < (CURRENT_TIMESTAMP - INTERVAL '{{ .Values.configMaps.dbCleanupScript.retentionPeriods.processedNotifications }}');

    -- Archive audit logs older than {{ .Values.configMaps.dbCleanupScript.retentionPeriods.auditLogs }}
    DELETE FROM vlan_change_log
    WHERE changed_at < (CURRENT_TIMESTAMP - INTERVAL '{{ .Values.configMaps.dbCleanupScript.retentionPeriods.auditLogs }}');

    -- Vacuum and analyze tables for performance
    VACUUM ANALYZE device_status;
    VACUUM ANALYZE notification_queue;
    VACUUM ANALYZE vlan_change_log;
{{- end }}