# Default values for oauth2-proxy
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/oauth2-proxy/oauth2-proxy
  pullPolicy: IfNotPresent
  tag: "v7.4.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 4180
  targetPort: 4180
  name: http

ingress:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

# OAuth2 Proxy Configuration
oauth2Proxy:
  # Provider configuration
  provider: "oidc"
  oidcIssuerUrl: "https://auth.scheeps.online/realms/scheeps"
  clientId: "" # e.g. vlan-manager

  # URLs
  redirectUrl: "" # e.g. https://vlan.scheeps.online/oauth2/callback
  upstreams: "" # e.g. http://vlan-manager-frontend.network-management.svc.cluster.local:80
  # Note: Make sure to include port number for upstreams (e.g. :5678 for n8n)

  # Server configuration
  httpAddress: "0.0.0.0:4180"
  reverseProxy: true
  skipProviderButton: true

  # Cookie configuration
  cookieDomains: "" # e.g. vlan.scheeps.online
  cookieSecure: true
  cookiePath: "/"
  cookieSamesite: "lax"
  cookieRefresh: "1m"
  cookieExpire: "4h"

  # Authentication configuration
  emailDomains: "*"
  scope: "openid profile email roles"
  oidcGroupsClaim: "realm_access_roles"
  allowedGroups: "" # e.g. vlan-manager-admin,vlan-manager-user
  whitelistDomains: "auth.scheeps.online"

  # Headers
  setAuthorizationHeader: true
  setXAuthRequest: true
  passAuthorizationHeader: true

# Secret configuration
secrets:
  # Name of the secret containing client_secret and cookie_secret
  name: "" # e.g. vlan-auth-secret
  clientSecretKey: "client_secret"
  cookieSecretKey: "cookie_secret"

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext: {}

# Security context
securityContext: {}

# Service account
serviceAccount:
  create: true
  annotations: {}
  name: ""
