apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgbouncer.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "pgbouncer.selectorLabels" . }}
  template:
    metadata:
      labels: {{ include "pgbouncer.selectorLabels" . }}
    spec:
      containers:
      - name: pgbouncer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: POSTGRESQL_HOST
          value: {{ .Values.postgresql.host | quote }}
        - name: POSTGRESQL_PORT
          value: "{{ .Values.postgresql.port }}"
        - name: POSTGRESQL_USERNAME
          value: {{ .Values.postgresql.username | quote }}
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.passwordSecret }}
              key: password
        - name: PGBOUNCER_AUTH_TYPE
          value: {{ .Values.auth.type | quote }}
        - name: PGBOUNCER_POOL_MODE
          value: {{ .Values.auth.poolMode | quote }}
        - name: PGBOUNCER_DATABASE
          value: |-
{{ .Values.auth.databases | indent 12 }}
        resources:
{{ toYaml .Values.resources | indent 8 }}
        volumeMounts:
        - name: tls-certs
          mountPath: /opt/bitnami/pgbouncer/certs
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: {{ .Values.tls.serverTlsSecret }}