# Default values for pgbouncer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bitnami/pgbouncer
  tag: 1.24.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

postgresql:
  host: postgresql-cluster-rw.postgres-system.svc.cluster.local
  port: 5432
  username: postgres
  passwordSecret: postgresql-superuser

auth:
  type: scram-sha-256
  poolMode: transaction
  ignoreStartupParameters: ""
  database: ""
  minPoolSize: 5
  
  # New flexible user authentication options
  users: []
    # Example configurations:
    # - name: "app_user"  # Static username
    #   passwordSecret:
    #     name: "app-credentials" 
    #     key: "password"
    # - name: "readonly_user"  # Static username
    #   password: "plain_password"  # Will be auto-hashed to SCRAM
    # - usernameSecret:  # Username from secret
    #     name: "app-credentials"
    #     key: "username"
    #   passwordSecret:
    #     name: "app-credentials"
    #     key: "password"
    # - usernameSecret:  # Username from secret with plain password
    #     name: "readonly-credentials"
    #     key: "username"
    #   password: "plain_password"
  
  # External userlist from ConfigMap or Secret
  externalUserlist:
    enabled: false
    # configMap:
    #   name: "pgbouncer-users"
    #   key: "userlist"
    # secret:
    #   name: "pgbouncer-users"
    #   key: "userlist"
  
  # Legacy static userlist (backward compatibility)
  userlist: |
    "<Username>" "<SCRAM Password>"

tls:
  enabled: true
  serverTlsSecret: pgbouncer-postgres-tls
  sslMode: verify-full

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

service:
  type: ClusterIP
  port: 5432

nodeSelector: {}

tolerations: []

affinity: {}

# Security context
securityContext: {}
podSecurityContext: {}
