{{/* Pull and decode the JWT */}}
{{- $jwt := (lookup "v1" "Secret" .Release.Namespace "opencloud-jwt-secret").data.jwt_secret | b64dec }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "opencloud.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque

stringData:
  # Kubernetes will base64-encode this for you.
  config.yaml: |+
    token_manager:
      jwt_secret: {{ $jwt | quote }}
    # …any other config you need…