apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencloud-custom.fullname" . }}-config
  labels:
    {{- include "opencloud-custom.labels" . | nindent 4 }}
data:
  OCIS_URL: "https://{{ .Values.opencloud.domain }}"
  OCIS_LOG_LEVEL: {{ .Values.opencloud.logLevel | quote }}
  OCIS_LOG_COLOR: {{ .Values.opencloud.logColor | quote }}
  OCIS_LOG_PRETTY: {{ .Values.opencloud.logPretty | quote }}
  OCIS_INSECURE: {{ .Values.opencloud.insecure | quote }}
  
  # Configuration directory
  OCIS_CONFIG_DIR: "{{ .Values.storage.config.mountPath }}"
  OCIS_CONFIG_FILE: "{{ .Values.storage.config.mountPath }}/ocis.yaml"
  
  # Cache directory
  OCIS_CACHE_DIR: "{{ .Values.storage.cache.mountPath }}"
  
  # Database configuration
  {{- if .Values.database.external.enabled }}
  STORAGE_USERS_DRIVER: "sql"
  STORAGE_USERS_SQL_DSN: "postgres://{{ .Values.database.external.username }}:$(DB_PASSWORD)@{{ .Values.database.external.host }}:{{ .Values.database.external.port }}/{{ .Values.database.external.database }}?sslmode={{ .Values.database.external.sslmode }}"
  STORAGE_GROUPS_DRIVER: "sql"
  STORAGE_GROUPS_SQL_DSN: "postgres://{{ .Values.database.external.username }}:$(DB_PASSWORD)@{{ .Values.database.external.host }}:{{ .Values.database.external.port }}/{{ .Values.database.external.database }}?sslmode={{ .Values.database.external.sslmode }}"
  {{- end }}
  
  # Storage configuration
  STORAGE_HOME_DRIVER: "posix"
  STORAGE_USERS_POSIX_ROOT: "{{ .Values.storage.data.mountPath }}"
  
  # Gateway and proxy configuration
  GATEWAY_GRPC_ADDR: "0.0.0.0:9142"
  PROXY_HTTP_ADDR: "0.0.0.0:9200"
  
  # Basic auth settings
  {{- if .Values.opencloud.enableBasicAuth }}
  PROXY_ENABLE_BASIC_AUTH: "true"
  {{- end }}
  
  # Demo users
  {{- if .Values.opencloud.createDemoUsers }}
  IDM_CREATE_DEMO_USERS: "true"
  {{- end }}
  
  # Cache settings for better performance
  CACHE_STORE: "memory"
  CACHE_STORE_NODES: "127.0.0.1:9233"
  CACHE_TTL: "300s"
  
  # Additional performance settings
  OCIS_EVENTS_ENABLE_TLS: "false"
  OCIS_GRPC_PROTOCOL: "tcp"