apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencloud.fullname" . }}-frontend-config
  namespace: opencloud
data:
  config.json: |
    {
      "server": "https://cloud.scheeps.online",
      "openIdConnect": {
        "authority": "https://cloud.scheeps.online/.well-known/openid-configuration",
        "client_id": "web",
        "scope": "openid profile email"
      },
      "apps": ["files", "search", "admin-settings"],
      "options": {"tokenStorageLocal": true}
    }