{{--
Pull the raw jwt_secret value out of the existing Secret,
base64-decode it, and stash it in a variable.
--}}
{{- $jwt := (lookup "v1" "Secret" .Release.Namespace "opencloud-jwt-secret").data.jwt_secret | b64dec }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.fullname" . }}-config     # e.g. opencloud-opencloud-config
  labels:
    app.kubernetes.io/name: {{ include "opencloud.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque

data:
  # This is literally the /etc/opencloud/config.yaml that OCIS/OpenCloud expects.
  config.yaml: |+
    token_manager:
      jwt_secret: {{ $jwt | quote }}
    # (you can add any other top-level settings your cluster needs here)