apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencloud-custom.fullname" . }}
  labels:
    {{- include "opencloud-custom.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opencloud-custom.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opencloud-custom.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status.php
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /status.php
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.database.external.passwordSecret }}
                  name: {{ .Values.database.external.passwordSecret.name }}
                  key: {{ .Values.database.external.passwordSecret.key }}
                  {{- else }}
                  name: {{ include "opencloud-custom.fullname" . }}-db-secret
                  key: password
                  {{- end }}
            - name: OCIS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.opencloud.adminPasswordSecret }}
                  name: {{ .Values.opencloud.adminPasswordSecret.name }}
                  key: {{ .Values.opencloud.adminPasswordSecret.key }}
                  {{- else }}
                  name: {{ include "opencloud-custom.fullname" . }}-admin-secret
                  key: admin-password
                  {{- end }}
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "opencloud-custom.fullname" . }}-config
          volumeMounts:
            {{- if .Values.storage.data.enabled }}
            - name: data
              mountPath: {{ .Values.storage.data.mountPath }}
            {{- end }}
            {{- if .Values.storage.config.enabled }}
            - name: config
              mountPath: {{ .Values.storage.config.mountPath }}
            {{- end }}
            {{- if .Values.storage.cache.enabled }}
            - name: cache
              mountPath: {{ .Values.storage.cache.mountPath }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.storage.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.storage.data.claimName }}
        {{- end }}
        {{- if .Values.storage.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "opencloud-custom.fullname" . }}-config
        {{- end }}
        {{- if .Values.storage.cache.enabled }}
        - name: cache
          persistentVolumeClaim:
            claimName: {{ include "opencloud-custom.fullname" . }}-cache
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}