apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencloud.fullname" . }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opencloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opencloud.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      
      # Init container to run 'ocis init' and generate config
      initContainers:
        - name: ocis-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: 
            - /bin/sh
            - -c
            - |
              echo "Initializing OCIS configuration..."
              # Check if config already exists
              if [ ! -f "{{ .Values.storage.config.mountPath }}/ocis.yaml" ]; then
                echo "No existing config found. Running ocis init..."
                # Run ocis init to generate initial config
                OCIS_CONFIG_DIR="{{ .Values.storage.config.mountPath }}" \
                OCIS_INSECURE="{{ .Values.opencloud.insecure }}" \
                OCIS_URL="https://{{ .Values.opencloud.domain }}" \
                /usr/bin/ocis init --insecure
                echo "OCIS configuration initialized successfully."
              else
                echo "Existing config found at {{ .Values.storage.config.mountPath }}/ocis.yaml"
              fi
              echo "Init container completed."
          volumeMounts:
            {{- if .Values.storage.config.enabled }}
            - name: config
              mountPath: {{ .Values.storage.config.mountPath }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          
          # OpenCloud doesn't have a dedicated health endpoint
          # Using the main web interface for health checks
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 120  # OpenCloud needs time to initialize all services
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 60   # Allow services to start before accepting traffic
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          
          env:
            # Override specific secrets after init
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.external.passwordSecret.name }}
                  key: {{ .Values.database.external.passwordSecret.key }}
            - name: IDM_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.opencloud.adminPasswordSecret.name }}
                  key: {{ .Values.opencloud.adminPasswordSecret.key }}
            # Note: OCIS_JWT_SECRET is generated by ocis init and stored in config file
            # Environment variables override config, so we let init handle JWT secret generation
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          
          envFrom:
            - configMapRef:
                name: {{ include "opencloud.fullname" . }}-config
          
          volumeMounts:
            {{- if .Values.storage.data.enabled }}
            - name: data
              mountPath: {{ .Values.storage.data.mountPath }}
            {{- end }}
            {{- if .Values.storage.config.enabled }}
            - name: config
              mountPath: {{ .Values.storage.config.mountPath }}
            {{- end }}
            {{- if .Values.storage.cache.enabled }}
            - name: cache
              mountPath: {{ .Values.storage.cache.mountPath }}
            {{- end }}
          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      
      volumes:
        {{- if .Values.storage.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.storage.data.claimName }}
        {{- end }}
        {{- if .Values.storage.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.storage.config.claimName }}
        {{- end }}
        {{- if .Values.storage.cache.enabled }}
        - name: cache
          persistentVolumeClaim:
            claimName: {{ .Values.storage.cache.claimName }}
        {{- end }}
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}