apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencloud.fullname" . }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opencloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opencloud.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: debug-config
          image: busybox
          command: ["sh", "-c", "ls -l /etc/opencloud && cat /etc/opencloud/opencloud.yaml || echo 'no config'"]
          volumeMounts:
            - name: config
              mountPath: {{ .Values.storage.config.mountPath }}
        - name: opencloud-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["sh", "-c", "opencloud init --insecure yes || true"]
          volumeMounts:
            - name: config
              mountPath: {{ .Values.storage.config.mountPath }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        - name: debug-after-init
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "=== ENV VARS ===";
              env;
              echo "=== CONFIG FILE ===";
              ls -l /etc/opencloud;
              cat /etc/opencloud/opencloud.yaml || echo 'no config after init';
          volumeMounts:
            - name: config
              mountPath: {{ .Values.storage.config.mountPath }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "opencloud server"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: IDM_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.opencloud.adminPasswordSecret.name }}
                  key: {{ .Values.opencloud.adminPasswordSecret.key }}
          envFrom:
            - configMapRef:
                name: {{ include "opencloud.fullname" . }}-config
          volumeMounts:
            {{- if .Values.storage.data.enabled }}
            - name: data
              mountPath: {{ .Values.storage.data.mountPath }}
            {{- end }}
            {{- if .Values.storage.cache.enabled }}
            - name: cache
              mountPath: {{ .Values.storage.cache.mountPath }}
            {{- end }}
            - name: config
              mountPath: {{ .Values.storage.config.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.storage.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.storage.data.claimName }}
        {{- end }}
        {{- if .Values.storage.cache.enabled }}
        - name: cache
          persistentVolumeClaim:
            claimName: {{ .Values.storage.cache.claimName }}
        {{- end }}
        {{- if .Values.storage.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.storage.config.claimName }}
        {{- else }}
        - name: config
          emptyDir: {}
        {{- end }}