# This file is now optional - only creates secrets if you're not using existing ones
# If you're using existing secrets, you can delete this file entirely

{{- if not .Values.database.external.passwordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud-custom.fullname" . }}-db-secret
  labels:
    {{- include "opencloud-custom.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.external.password | b64enc | quote }}
---
{{- end }}

{{- if not .Values.opencloud.adminPasswordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud-custom.fullname" . }}-admin-secret
  labels:
    {{- include "opencloud-custom.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.opencloud.adminPassword | b64enc | quote }}
{{- end }}