apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencloud.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "opencloud.name" . }}
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- end }}
  {{- if .Values.service.port }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
  {{- end }}