apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencloud.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "opencloud.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}