apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oauth2-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oauth2-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oauth2-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: OAUTH2_PROXY_PROVIDER
          value: {{ .Values.oauth2Proxy.provider | quote }}
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: {{ .Values.oauth2Proxy.oidcIssuerUrl | quote }}
        - name: OAUTH2_PROXY_CLIENT_ID
          value: {{ .Values.oauth2Proxy.clientId | quote }}
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: {{ .Values.secrets.clientSecretKey }}
        - name: OAUTH2_PROXY_REDIRECT_URL
          value: {{ .Values.oauth2Proxy.redirectUrl | quote }}
        - name: OAUTH2_PROXY_UPSTREAMS
          value: {{ .Values.oauth2Proxy.upstreams | quote }}
        - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
          value: {{ .Values.oauth2Proxy.skipProviderButton | quote }}
        - name: OAUTH2_PROXY_REVERSE_PROXY
          value: {{ .Values.oauth2Proxy.reverseProxy | quote }}
        - name: OAUTH2_PROXY_HTTP_ADDRESS
          value: {{ .Values.oauth2Proxy.httpAddress | quote }}
        - name: OAUTH2_PROXY_COOKIE_DOMAINS
          value: {{ .Values.oauth2Proxy.cookieDomains | quote }}
        - name: OAUTH2_PROXY_COOKIE_SECURE
          value: {{ .Values.oauth2Proxy.cookieSecure | quote }}
        - name: OAUTH2_PROXY_COOKIE_PATH
          value: {{ .Values.oauth2Proxy.cookiePath | quote }}
        - name: OAUTH2_PROXY_COOKIE_SAMESITE
          value: {{ .Values.oauth2Proxy.cookieSamesite | quote }}
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: {{ .Values.secrets.cookieSecretKey }}
        - name: OAUTH2_PROXY_EMAIL_DOMAINS
          value: {{ .Values.oauth2Proxy.emailDomains | quote }}
        - name: OAUTH2_PROXY_SCOPE
          value: {{ .Values.oauth2Proxy.scope | quote }}
        - name: OAUTH2_PROXY_OIDC_GROUPS_CLAIM
          value: {{ .Values.oauth2Proxy.oidcGroupsClaim | quote }}
        - name: OAUTH2_PROXY_ALLOWED_GROUPS
          value: {{ .Values.oauth2Proxy.allowedGroups | quote }}
        - name: OAUTH2_PROXY_SET_AUTHORIZATION_HEADER
          value: {{ .Values.oauth2Proxy.setAuthorizationHeader | quote }}
        - name: OAUTH2_PROXY_SET_XAUTHREQUEST
          value: {{ .Values.oauth2Proxy.setXAuthRequest | quote }}
        - name: OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER
          value: {{ .Values.oauth2Proxy.passAuthorizationHeader | quote }}
        - name: OAUTH2_PROXY_WHITELIST_DOMAINS
          value: {{ .Values.oauth2Proxy.whitelistDomains | quote }}
        - name: OAUTH2_PROXY_COOKIE_REFRESH
          value: {{ .Values.oauth2Proxy.cookieRefresh | quote }}
        - name: OAUTH2_PROXY_COOKIE_EXPIRE
          value: {{ .Values.oauth2Proxy.cookieExpire | quote }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}