apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto-mqtt.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mosquitto-mqtt.labels" . | nindent 4 }}
data:
  mosquitto.conf: |
    password_file /mosquitto/config/passwd
    
    listener 1883
    allow_anonymous false
    
    listener 9001
    protocol websockets
    allow_anonymous false
    
    log_dest stdout
    {{- range .Values.mqtt.logging.logTypes }}
    log_type {{ . }}
    {{- end }}
    connection_messages {{ .Values.mqtt.logging.connectionMessages }}